adhotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user.views import activate
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += i18n_patterns(
    path('', include('hotels.urls')),
    path('auth/', include('user.urls')),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activate, name='activate'),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

hotels/urls.py
from django.urls import path
from .views import *
from user.views import registration, userLogin, userLogout

urlpatterns = [
    path('', index, name='index'),
    path('hotels/', hotelList, name='hotel-list'),
    path('<int:hid>', hotelDetails, name='details-page'),
    path('add/', addHotel, name='add-hotel'),
    path('<int:hid>/edit/', editHotel, name='edit-hotel'),
    path('<int:hid>/delete/', deleteHotel, name='delete-hotel'),
    path('registration/', registration, name='registr'),
    path('login/', userLogin, name='login'),
    path('logout/', userLogout, name='logout'),
    path('<int:hid>/new-review/', add_review, name='add_review'),
    path('<int:rid>/room-details/', room_details, name='room-details'),
    path('<int:hid>/new-room/', add_room, name='add-room'),
    path('<int:rid>/edit-room/', edit_room, name='edit-room'),
    path('<int:rid>/delete-room/', delete_room, name='delete-room'),
    path('<int:bid>/booking-details/', booking_details, name='booking-details'),
    path('<int:rid>/create-booking/', create_booking, name='create-booking'),
    path('<int:bid>/edit-booking/', edit_booking, name='edit-booking'),
    path('<int:bid>/delete-booking/', delete_booking, name='delete-booking'),
    path('bookings/', booking_list, name='booking-list'),
    path('search/', search_results, name='search-results'),
]

user/urls.py
from django.urls import path
from .views import registration, userLogin, userLogout, profile, update_profile, delete_profile

urlpatterns = [
    path('registration/', registration, name='registr'),
    path('login/', userLogin, name='login'),
    path('logout/', userLogout, name='logout'),
    path('profile/<int:uid>/', profile, name='profile'), 
    path('update-profile/<int:uid>/', update_profile, name='update-profile'), 
    path('delete-profile/<int:uid>/', delete_profile, name='delete-profile'),
]

hotels/models.py
from django.db import models
from django.utils import timezone
from user.models import User

# Create your models here.

class Hotel(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    address = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    class Star(models.IntegerChoices):
        Tourist_1_star = 1
        Standart_2_star = 2
        Comfort_3_star = 3
        First_Class_4_star = 4
        Luxury_5_star = 5
    star = models.IntegerField(choices = Star, default=0, verbose_name='Category')
    num_rooms = models.IntegerField(verbose_name='number of rooms')
    services = models.TextField()
    time_stamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.name} {'★' * self.star}, {self.num_rooms} rooms"
    
class Room(models.Model):
    capacity_choices = [
        (1, '1 person'),
        (2, '2 people'),
        (3, '3 people'),
        (4, '4 people'),
    ]
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    room_type = models.CharField(max_length=255)
    capacity = models.IntegerField(choices=capacity_choices)
    description = models.TextField()
    price_per_night = models.DecimalField(max_digits=10, decimal_places=2)
    # is_available = models.BooleanField(default=True)

    @property
    def is_available(self):
        active_bookings = self.bookings.filter(check_out__gt=timezone.now())
        return not active_bookings.exists()
    def __str__(self):
        return f'{self.hotel.name} : {self.room_type}'
    
class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='bookings')
    check_in = models.DateField()
    check_out = models.DateField()
    guests = models.PositiveIntegerField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name} : {self.room.hotel} {self.room} from {self.check_in} to {self.check_out}'



class HotelAttachment(models.Model):
    name = models.CharField(blank=True, null=True)
    image = models.ImageField(upload_to='images')
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        image_name = self.image.name.split('.')[0]
        self.name = image_name
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.image}'
    
class Review(models.Model):
    rating_choices = [
        (1, '1.0'), (2, '2.0'), (3, '3.0'), (4, '4.0'),
        (5, '5.0'), (6, '6.0'), (7, '7.0'),
        (8, '8.0'), (9, '9.0'), (10, '10'),
    ]
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=rating_choices)
    comment = models.TextField()
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    time_stamp = models.DateField(default=timezone.now)

    def __str__(self):
        return f'{self.author} : {self.hotel.name} {self.time_stamp}'



class RoomAttachment(models.Model):
    name = models.CharField(blank=True, null=True)
    image = models.ImageField(upload_to='images')
    room = models.ForeignKey(Room, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        image_name = self.image.name.split('.')[0]
        self.name = image_name
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.image}'
    

hotels/views.py
from django.shortcuts import render, redirect
from .models import Hotel, HotelAttachment, Review, Room, RoomAttachment, Booking
from .form import Hotelform, ReviewForm, RoomForm, BookingFrom
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Prefetch

# Create your views here.

def hotelList(request):
    hotels = Hotel.objects.all()
    for hotel in hotels:
        att = HotelAttachment.objects.filter(hotel_id = hotel.pk)
        hotel.images = att
    return render(request, 'hotels/hotel_list.html', {'hotels': hotels})

def hotelDetails(request, hid):
    hotel = Hotel.objects.get(pk = hid)
    att = HotelAttachment.objects.filter(hotel_id = hid)
    rooms = Room.objects.filter(hotel=hotel)
    available_rooms = [room for room in rooms if room.is_available]
    services = hotel.services.split(', ')
    reviews = Review.objects.filter(hotel=hotel)
    return render(request, 'hotels/details_page.html', {
        'hotel': hotel, 
        'images': att, 
        'rooms': available_rooms, 
        'services': services, 
        'reviews': reviews,})

@login_required
def addHotel(request):
    if request.method != 'POST':
        form = Hotelform()
    else: 
        form = Hotelform(request.POST)
        att = request.FILES.getlist('images')
        if form.is_valid():
            hotel = form.save(commit=False)
            hotel.author = request.user
            print("FILES:", request.FILES.getlist('images'))
            hotel.save()
            for img in att:
                HotelAttachment.objects.create(hotel_id = hotel.pk, image=img)
        return redirect(to='details-page', hid=hotel.pk)
    return render(request, 'hotels/new_hotel.html', {'form': form}) 

@login_required
def editHotel(request, hid):
    hotel = Hotel.objects.get(pk=hid)
    hotel_att = HotelAttachment.objects.filter(hotel_id=hid)
    if request.method != 'POST':
        form = Hotelform(instance=hotel)
    else: 
        form = Hotelform(request.POST, instance=hotel)
        if form.is_valid():
            hotel = form.save(commit=False)
            att = request.FILES.getlist('images')
            for img in att:
                HotelAttachment.objects.create(hotel_id = hotel.pk, image=img)
            chosen = request.POST.getlist('attachments')
            for img_id in chosen:
                HotelAttachment.objects.filter(pk=int(img_id)).delete()
            hotel.save()
        return redirect(to='details-page', hid=hotel.pk)
    return render(request, 'hotels/edit_hotel.html', {'form': form, 'hotel_att':hotel_att}) 

@login_required
def deleteHotel(request, hid):
    hotel = Hotel.objects.get(pk=hid)
    hotel.delete()
    return redirect(to='hotel-list')

def index(request):
    return render(request, 'hotels/index.html')

@login_required
def add_review(request, hid):
    if request.method != 'POST':
        form = ReviewForm()
    else:
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.hotel_id = hid
            review.author = request.user
            review.save()
            return redirect('details-page', hid=hid)
    return render(request, 'hotels/new_review.html', {'form': form})

def room_details(request, rid):
    room = Room.objects.get(pk = rid)
    att = RoomAttachment.objects.filter(room_id = rid)
    return render(request, 'hotels/room_details.html', {'room': room, 'images': att})

@login_required
def add_room(request, hid):
    if request.method != 'POST':
        form = RoomForm()
    else:
        form = RoomForm(request.POST)
        att = request.FILES.getlist('images')
        if form.is_valid():
            room = form.save(commit=False)
            room.author = request.user
            room.hotel_id = hid
            room.save()
            for img in att:
                RoomAttachment.objects.create(room=room, image=img)
            return redirect('details-page', hid=hid)
    return render(request, 'hotels/new_room.html', {'form': form})

@login_required
def edit_room(request, rid):
    room = Room.objects.get(pk=rid)
    hotel = room.hotel
    room_att = RoomAttachment.objects.filter(room_id=rid)
    if request.method != 'POST':
        form = RoomForm(instance=room)
    else:
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            room = form.save(commit=False)
            att = request.FILES.getlist('images')
            for img in att:
                RoomAttachment.objects.create(room_id=room.pk, image=img)
            chosen = request.POST.getlist('attachments')
            for img_id in chosen:
                RoomAttachment.objects.filter(pk=int(img_id)).delete()
            room.save()
        return redirect(to='room-details', rid=room.pk)
    return render(request, 'hotels/edit_room.html', {'form': form, 'room_att':room_att})    

@login_required
def delete_room(request, rid):
    room = Room.objects.get(pk=rid)
    hotel_id = room.hotel.pk
    room.delete()
    return redirect(to='details-page', hid=hotel_id)

@login_required
def booking_list(request):
    bookings = Booking.objects.filter(user=request.user).select_related('room__hotel')
    return render(request, 'hotels/booking_list.html', {'bookings': bookings})

@login_required
def booking_details(request, bid):
    booking = Booking.objects.get(pk=bid)
    return render(request, 'hotels/booking_details.html', {'booking': booking})

@login_required
def create_booking(request, rid):
    room = Room.objects.get(pk=rid)
    if request.method != 'POST':
        form = BookingFrom()
    else:
        form = BookingFrom(request.POST)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.user = request.user
            booking.room = room
            booking.save()
            return redirect(to='booking-details', bid=booking.pk)
        else:
            print(form.errors)
    return render(request, 'hotels/new_booking.html', {'form': form})

@login_required
def edit_booking(request, bid):
    booking = Booking.objects.get(pk=bid)
    if request.method != 'POST':
        form = BookingFrom(instance=booking)
    else:
        form = BookingFrom(request.POST, instance=booking)
        if form.is_valid():
            booking = form.save()
        return redirect(to='booking-details', bid=booking.pk)
    return render(request, 'hotels/edit_booking.html', {'form': form})

@login_required
def delete_booking(request, bid):
    booking = Booking.objects.get(pk=bid)
    hotel_id = booking.room.hotel.id
    booking.delete()
    return redirect(to='details-page', hid=hotel_id)

def search_results(request):
    query = request.GET.get('q', '')
    checkin = request.GET.get('checkin')
    checkout = request.GET.get('checkout')

    hotels = []
    if query:
        hotels = Hotel.objects.filter(
            Q(name__icontains=query) |
            Q(address__icontains=query) |
            Q(description__icontains=query)
        ).prefetch_related(
            Prefetch('room_set', queryset=Room.objects.order_by('price_per_night')),
            Prefetch('hotelattachment_set')
        )

    # Формируем список отелей с нужными данными
    results = []
    for hotel in hotels:
        room = hotel.room_set.first()
        image = hotel.hotelattachment_set.first()
        results.append({
            'id': hotel.id,
            'name': hotel.name,
            'address': hotel.address,
            'star': hotel.star,
            'room': {
                'price_per_night': room.price_per_night if room else 'N/A'
            },
            'images': [image] if image else [],
        })

    return render(request, 'hotels/search_results.html', {
        'query': query,
        'checkin': checkin,
        'checkout': checkout,
        'results': results,
        'destination': query,
        'results_count': len(results)
    })

templates/hotels/booking_details.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
Booking details | HotelBooking
{% endblock title %}

{% block content %}
<div class="booking-container">
    <div class="booking-card">
        <h2 class="booking-title">{% trans 'Booking Details' %}</h2>
        
        <div class="booking-info">
            <div class="info-item">
                <span class="info-label">{% trans 'Hotel:' %}</span>
                <span class="info-value">{{ booking.room.hotel.name }}</span>
            </div>
            <div class="info-item">
                <span class="info-label">{% trans 'Check-in:' %}</span>
                <span class="info-value">{{ booking.check_in }}</span>
            </div>
            <div class="info-item">
                <span class="info-label">{% trans 'Room Type:' %}</span>
                <span class="info-value">{{ booking.room.room_type }}</span>
            </div>
            <div class="info-item">
                <span class="info-label">{% trans 'Check-out:' %}</span>
                <span class="info-value">{{ booking.check_out }}</span>
            </div>
            <div class="info-item">
                <span class="info-label">{% trans 'Guests:' %}</span>
                <span class="info-value">{{ booking.guests }}</span>
            </div>
            <div class="info-item">
                <span class="info-label">{% trans 'Booking Date:' %}</span>
                <span class="info-value">{{ booking.created_at }}</span>
            </div>
        </div>

        {% if user.is_authenticated and user.id == booking.user.id %}
        <div class="booking-actions">
            <a href="{% url 'edit-booking' bid=booking.pk %}" class="btn btn-edit">
                {% trans 'Edit' %}
            </a>
            <a href="{% url 'delete-booking' bid=booking.pk %}" class="btn btn-delete">
                {% trans 'Delete' %}
            </a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/hotels/booking_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
Booking list | HotelBooking
{% endblock title %}

{% block content %}
<div class="bookings-container">
    <h2 class="bookings-title">{% trans 'Your Bookings' %}</h2>
    
    {% if bookings %}
    <div class="bookings-list">
        {% for booking in bookings %}
        <div class="booking-card">
            <a href="{% url 'booking-details' bid=booking.pk %}" class="booking-link">
                <div class="booking-header">
                    <h3 class="hotel-name">{{ booking.room.hotel.name }}</h3>
                    <span class="booking-status">{% trans 'Confirmed' %}</span>
                </div>
                
                <div class="booking-dates">
                    <div class="date-group">
                        <span class="date-label">{% trans 'Check-in:' %}</span>
                        <span class="date-value">{{ booking.check_in|date:"M d, Y" }}</span>
                    </div>
                    <div class="date-group">
                        <span class="date-label">{% trans 'Check-out:' %}</span>
                        <span class="date-value">{{ booking.check_out|date:"M d, Y" }}</span>
                    </div>
                </div>
                
                <div class="booking-meta">
                    <span class="meta-item">{% trans 'Booking Date:' %} {{ booking.created_at|date:"M d, Y" }}</span>
                    <span class="meta-item">{% trans 'Room:' %} {{ booking.room.room_type }}</span>
                </div>
            </a>
        </div>
    {% endfor %}
    </div>
    {% else %}
    <div class="no-bookings">
        <p>{% trans "You don't have any bookings yet." %}</p>
    </div>
    {% endif %}
</div>
{% endblock content %}

templates/hotels/details_page.html
{% extends "base.html" %}
{% load hotel_filters static i18n %}

{% block title %}
Hotel details | HotelBooking
{% endblock title %}

{% block content %}
    <div class="hotel-description">
        <h1>{{hotel.name}}</h1>
        <h3>{% for i in "12345" %}
        {% if forloop.counter <= hotel.star %}
            ★
        {% endif %}
        {% endfor %}</h3>

    <section class="room-photo-carousel">
        <div class="carousel-wrapper">
            {% if images|length > 2 %}
                <button class="carousel-btn left">&#10094;</button>
            {% endif %}
            
            <div class="carousel">
                {% for image in images %}
                    <div class="category-card">
                        <img src="{{ image.image.url }}" alt="Room image" class="hotel-main-image">
                    </div>
                {% endfor %}
            </div>
            
            {% if images|length > 2 %}
                <button class="carousel-btn right">&#10095;</button>
            {% endif %}
        </div>
    </section>

        <p>{{hotel.description}}</p>

        <h2>{% trans 'Facilities of' %} {{hotel.name}}:</h2>
        <div class="amenities">
            {% for service in services %}
                <span class="amenity">{{ service }}</span>
            {% endfor %}
        </div>

        <p><i class="fi fi-rs-marker"></i><strong>Address: </strong>{{hotel.address}}</p>

        <h2>{% trans 'Available Rooms' %}</h2>
        {% if rooms %}
            <table class="room-table">
                <thead>
                    <tr>
                        <th>{% trans 'Room Type' %}</th>
                        <th>{% trans 'Capacity' %}</th>
                        <th>{% trans 'Description' %}</th>
                        <th>{% trans 'Price per Night' %}</th>
                        <th>{% trans 'Status' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for room in rooms %}
                        <tr>
                            <td>
                                <a href="{% url 'room-details' rid=room.pk %}">
                                    {{ room.room_type }}
                                </a>
                            </td>
                            <td>{{ room.capacity }} {% trans 'guests' %}</td>
                            <td>{{ room.description|cut_after_dot }}</td>
                            <td>{{ room.price_per_night }} KZT</td>
                            <td>
                                {% if room.is_available %}
                                    <span class="available">{% trans 'Available' %}</span>
                                {% else %}
                                    <span class="unavailable">{% trans 'Not available' %}</span>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>{% trans 'No available rooms at the moment.' %}</p>
        {% endif %}

        {% if user.is_authenticated and user.is_staff %}
        <div class="admin-actions">
            <a href="{% url 'add-room' hid=hotel.pk %}" class="admin-btn">{% trans 'Add room' %}</a>
        </div>
        {% endif %}
    </div>

    {% if user.is_authenticated and user.is_staff %}
    <div class="admin-actions">
        <a href="{% url 'edit-hotel' hid=hotel.pk %}" class="admin-btn">{% trans 'Edit' %}</a>
        <a href="{% url 'delete-hotel' hid=hotel.pk %}" class="admin-btn">{% trans 'Delete' %}</a>
    </div>
    {% endif %}

    <div class="reviews">
        <div class="reviews-header">
            <h2>{% trans 'Guest Reviews' %}</h2>
            {% if user.is_authenticated %}
                <a href="{% url 'add_review' hid=hotel.pk %}" class="write-review-btn">{% trans 'Write a review' %}</a>
            {% endif %}
        </div>

        {% for review in reviews %}
            <div class="review-card">
                <div class="review-left">
                    <p class="author">{{ review.author.first_name }} {{ review.author.last_name }}</p>
                    <p class="comment">{{ review.comment }}</p>
                    <p class="timestamp">{{ review.time_stamp }}</p>
                </div>
                <div class="review-right">
                    <span class="rating">{{ review.rating }}</span>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock  %}

templates/hotels/edit_booking.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
Edit Booking | HotelBooking
{% endblock title %}

{% block content %}
<div class="form-container">
    <h1>{% trans 'Edit booking information' %}</h1>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {% if field.errors %}
                    <div class="error-message">{{ field.errors|striptags }}</div>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="btn">{% trans 'Save' %}</button>
    </form>
</div>
{% endblock content %}

templates/hotels/edit_hotel.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
Edit hotel | HotelBooking
{% endblock title %}

{% block content %}
<div class="form-container">
    <h2>{% trans 'Edit Hotel' %}</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {% if field.errors %}
                    <div class="error-message">{{ field.errors|striptags }}</div>
                {% endif %}
            </div>
        {% endfor %}

<div class="image-management-section">
    <!-- Существующие изображения с чекбоксами для удаления -->
    {% if hotel_att %}
    <div class="existing-images-section">
        <label class="section-label">{% trans 'Existing images (select to delete):' %}</label>
        <div class="image-grid">
            {% for img in hotel_att %}
            <div class="image-checkbox-block">
                <label class="image-checkbox-label">
                    <input type="checkbox" name="attachments" value="{{ img.pk }}" class="image-checkbox">
                    <img src="{{ img.image.url }}" alt="Hotel image" class="image-preview">
                    <span class="checkbox-overlay">
                        <svg viewBox="0 0 24 24" class="check-icon">
                            <path d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"/>
                        </svg>
                    </span>
                </label>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}

    <!-- Загрузка новых изображений -->
    <div class="image-upload-section">
        <label class="section-label">{% trans 'Upload new images:' %}</label>
        <div class="upload-control">
            <label for="image-input" class="upload-btn">
                <svg viewBox="0 0 24 24" class="upload-icon">
                    <path d="M14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V8L14,2M18,20H6V4H13V9H18V20M8,15V13H16V15H8M8,11V9H16V11H8Z"/>
                </svg>
                <span>{% trans 'Select Files' %}</span>
            </label>
            <input type="file" name="images" multiple id="image-input" onchange="show_files_name(this)" class="file-input">
            <div class="file-names" id="file-names-display"></div>
        </div>
    </div>
</div>
        {% if room_att %}
            <p style="font-size: 14px; color: #555;">{% trans 'Selected images will be deleted after saving.' %}</p>
        {% endif %}
        <button type="submit" class="btn">{% trans 'Save' %}</button>
    </form>
</div>
{% endblock %}

templates/hotels/edit_room.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
Edit room | HotelBooking
{% endblock title %}

{% block content %}
<div class="form-container">
    <h2>{% trans 'Edit Room' %}</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {% if field.errors %}
                    <div class="error-message">{{ field.errors|striptags }}</div>
                {% endif %}
            </div>
        {% endfor %}

<div class="image-management-section">
    <!-- Существующие изображения с чекбоксами для удаления -->
    {% if room_att %}
    <div class="existing-images-section">
        <label class="section-label">{% trans 'Existing images (select to delete):' %}</label>
        <div class="image-grid">
            {% for img in room_att %}
            <div class="image-checkbox-block">
                <label class="image-checkbox-label">
                    <input type="checkbox" name="attachments" value="{{ img.pk }}" class="image-checkbox">
                    <img src="{{ img.image.url }}" alt="Hotel image" class="image-preview">
                    <span class="checkbox-overlay">
                        <svg viewBox="0 0 24 24" class="check-icon">
                            <path d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"/>
                        </svg>
                    </span>
                </label>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}

    <!-- Загрузка новых изображений -->
    <div class="upload-section">
        <label class="section-label">{% trans 'Upload new images:' %}</label>
        <div class="upload-control">
            <label for="image-input" class="upload-btn">
                <svg viewBox="0 0 24 24" class="upload-icon">
                    <path d="M14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V8L14,2M18,20H6V4H13V9H18V20M8,15V13H16V15H8M8,11V9H16V11H8Z"/>
                </svg>
                <span>{% trans 'Select Files' %}</span>
            </label>
            <input type="file" name="images" multiple id="image-input" onchange="show_files_name(this)" class="file-input">
            <div class="file-names" id="file-names-display"></div>
        </div>
    </div>
</div>
        <button type="submit" class="btn">{% trans 'Save' %}</button>
    </form>
</div>
{% endblock %}

templates/hotels/hotel_list.html
{% extends "base.html" %}
{% load hotel_filters static i18n %}

{% block title %}
Hotel list | HotelBooking
{% endblock title %}

{% block content %}
    <h1>{% trans 'Our hotels' %}</h1>

    {% if user.is_authenticated and user.is_staff %} 
    <div class="admin-actions">
        <a href="{% url 'add-hotel' %}" class="admin-btn">{% trans 'New hotel' %}</a>
    </div>
    {% endif %}
    <div class="hotels-grid">
        {% for hotel in hotels %}
                <div class="hotel-card">
                    <img src="{{hotel.images.0.image.url}}" alt="{{hotel.name}}">
                    <div class="card-content">
                        <h3>{{hotel.name}}</h3>
                        <h3>{% for i in "12345" %}
                        {% if forloop.counter <= hotel.star %}
                            ★
                        {% endif %}
                        {% endfor %}</h3>
                        <p>{{hotel.description|cut_after_dot}}</p>
                        <a href="{% url 'details-page' hid=hotel.pk %}" class="btn">{% trans 'More info' %}</a>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock  %}

templates/hotels/room_details.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
Room details | HotelBooking
{% endblock title %}

{% block content %}
<div class="room-details-container">
    <div class="room-details-images">
        <div class="image-gallery">
            {% for image in images %}
                <img src="{{ image.image.url }}" alt="Room image">
            {% endfor %}
        </div>
    </div>

    <div class="room-details-content">
        <p class="room-type">{{ room.room_type }}</p>
        <p><strong>{% trans 'Capacity' %}:</strong> {{ room.get_capacity_display }}</p>
        <p><strong>{% trans 'Description' %}:</strong></p>
        <p>{{ room.description }}</p>
        <p><strong>{% trans 'Price per night' %}:</strong> {{ room.price_per_night }} KZT</p>
        {% if room.is_available %}
            <p class="available">{% trans '✓ Available' %}</p>
        {% else %}
            <p class="unavailable">{% trans '✗ Not available' %}</p>
        {% endif %}
    </div>

    <div class="room-details-actions">
        {% if user.is_authenticated %}
            <a href="{% url 'create-booking' rid=room.pk %}">
                <button>{% trans 'Reserve' %}</button>
            </a>
        {% endif %}

        {% if user.is_authenticated and user.is_staff %}
            <a href="{% url 'edit-room' rid=room.pk %}">
                <button>{% trans 'Edit' %}</button>
            </a>
            <a href="{% url 'delete-room' rid=room.pk %}">
                <button>{% trans 'Delete' %}</button>
            </a>
        {% endif %}
    </div>
</div>
{% endblock content %}